### ISSUE TITLE
Regarding width of image

### ISSUE THREAD

**Issue by Pratham31** [windmichael/ng-image-as-particles#4]
Actually I am just playing around it and get to know that when you **inspect** the demo and close it you will find image size will be widened unexpectedly.

**Comment by windmichael** [comment]
Thanks for pointing out this issue. There is an issue when the browser window is resized. I will try to fix it in the next days.

**Comment by Pratham31** [comment]
Sure  👍

**Comment by Pratham31** [comment]
I will send you a combined JS file of mine by tomorrow...
