### ISSUE TITLE
Cannot find module 'ng-image-as-particles'.

### ISSUE THREAD

**Issue by anzen-digital** [windmichael/ng-image-as-particles#8]
@windmichael 
Hi I installed the library in his **version 1.1.0**, but when I import the module like in the documentation
`import { NgImageAsParticlesModule } from 'ng-image-as-particles';`

But throw me the following error:
`Cannot find module 'ng-image-as-particles'.`

My Angular version is **8.3.29**

**Comment by windmichael** [comment]
Hi,
sorry, there was a mistake when publishing the version 1.1.0.
I published a new version 1.1.1, which should work as expected. 
Please install the 'ng-image-as-particles' npm package version 1.1.1 and let me know, if it works for you now.

Best regards
Michael

**Comment by windmichael** [comment]
@anzen-digital is there any update on this issue? Otherwise I will close it in the next days.
